function Hd = ecgfilter
%ECGFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 20-Mar-2020 10:53:25

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency

N     = 17;  % Order
Fpass = 6;   % Passband Frequency
Fstop = 30;  % Stopband Frequency
Wpass = 1;   % Passband Weight
Wstop = 1;   % Stopband Weight
dens  = 20;  % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
